const ActionTypes = {
    SET_GOOGLE_KEY_DATA: 'SET_GOOGLE_KEY_DATA',
    SET_GOOGLE_KEY_ERROR: 'SET_GOOGLE_KEY_ERROR',
    SET_SOLAR_LOCATION: 'SET_SOLAR_LOCATION',
    ADD_SOLAR_RESULTS: 'ADD_SOLAR_RESULTS',
    SET_SOLAR_ERROR: 'SET_SOLAR_ERROR',
    CLEAR_ERRORS_AND_RESULTS: 'CLEAR_ERRORS_AND_RESULTS'
};

export default ActionTypes;
